version: "2"
services:
  redis:
    image: redis:latest

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 sendLive.asgi:channel_layer
    volumes:
      - .:/code
    links:
      - redis
    ports:
     - "8000:8000"
    depends_on:
      - db

  worker:
    build: .
    command: python manage.py runworker
    volumes:
      - .:/code
    links:
      - redis

  db:
    image: postgres
